// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUhCWRpO0LL5t_OVHOq15rFVrCv_7_Kb4',
    appId: '1:590211205002:web:db5364ee8255d679c9ea73',
    messagingSenderId: '590211205002',
    projectId: 'book-share-75c3b',
    authDomain: 'book-share-75c3b.firebaseapp.com',
    storageBucket: 'book-share-75c3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZFWdylEymJXHVQ1Rgujq-i87fVWPkAC8',
    appId: '1:590211205002:android:d91e038724659eb7c9ea73',
    messagingSenderId: '590211205002',
    projectId: 'book-share-75c3b',
    storageBucket: 'book-share-75c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApG40gDEm5eLaviTyL553EQXg6a4WktTU',
    appId: '1:590211205002:ios:05d14cddd2db6f51c9ea73',
    messagingSenderId: '590211205002',
    projectId: 'book-share-75c3b',
    storageBucket: 'book-share-75c3b.appspot.com',
    iosClientId: '590211205002-sebvhqetp08ab5ip1oktfrqce6hhdm04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApG40gDEm5eLaviTyL553EQXg6a4WktTU',
    appId: '1:590211205002:ios:05d14cddd2db6f51c9ea73',
    messagingSenderId: '590211205002',
    projectId: 'book-share-75c3b',
    storageBucket: 'book-share-75c3b.appspot.com',
    iosClientId: '590211205002-sebvhqetp08ab5ip1oktfrqce6hhdm04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );
}
